name: Link Check

on: [push, pull_request]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-mail README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
